### PR TITLE
Account for adoptium producing incorrect metadata for staticlibs

### PR DESCRIPTION
**Pull request by johnoliver**
# Checklist

- [ ] You added tests to cover the change
- [ ] `mvn clean install` build and test completes
- [ ] You changed or added to the documentation

### CODE REVIEW

**Review by jerboaa — COMMENTED** [review]
Why the special casing of static-libs? Shouldn't this be done for all image types (debugimage, testimage, jre, jdk)? Also note that latest runs have the correct metadata.

**Comment by johnoliver** [comment]
@jerboaa, it seems that the metadata file is only incorrect for staticlibs, the rest are fine

**Comment by sxa** [comment]
> it seems that the metadata file is only incorrect for staticlibs, the rest are fine

At the risk of asking a silly question, have we now fixed the metadata generation too?

**Review by gdams — APPROVED** [review]

**Comment by johnoliver** [comment]
@sxa https://github.com/adoptium/ci-jenkins-pipelines/commit/df113be6717b7c56acfd187b27ce828d45bf9fe9#diff-b4bb07e2f448f9ad2986d69423ad0b704dcdc4d217d947f465e6ace3fde7a4b3 should have done it

**Comment by jerboaa** [comment]
> @sxa [adoptium/ci-jenkins-pipelines@df113be#diff-b4bb07e2f448f9ad2986d69423ad0b704dcdc4d217d947f465e6ace3fde7a4b3](https://github.com/adoptium/ci-jenkins-pipelines/commit/df113be6717b7c56acfd187b27ce828d45bf9fe9#diff-b4bb07e2f448f9ad2986d69423ad0b704dcdc4d217d947f465e6ace3fde7a4b3) should have done it

Yes, and it did:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-hotspot/967/artifact/workspace/target/OpenJDK11U-static-libs-glibc_aarch64_linux_hotspot_2021-10-04-09-34.tar.gz.json

So it's weird to have this special case.

**Comment by sxa** [comment]
> So it's weird to have this special case.

Unless the API is tripping up on the ones published before that fix went in.

**Comment by jerboaa** [comment]
> > So it's weird to have this special case.
> 
> Unless the API is tripping up on the ones published before that fix went in.

Yes, that's the issue. Some nightlies had the wrong metadata. This patch is a band-aid to fix it.

**Pull request merged**
