### PR TITLE
[#124] use CommonMark for description fields

### LINKED ISSUE #124: HTML tags in field descriptions
**Describe the bug**

HTML tags in hints in input fields, see screenshot.

**To Reproduce**
1. Go to api.adoptium.net
2. Click on swagger docs
3. Scroll down to any API call with input fields
4. See html tags

**Expected behavior**

formatting

**Screenshots**

Screenshot 2021-08-04 at 08 31 48

**Device (please complete the following information):**

any

**Additional context**

Will file a PR later today

### PR DESCRIPTION
**Pull request by bmarwell**
* HTML is not supported.
* fixes #124.

# Checklist

- [ ] You added tests to cover the change
- [X] `mvn clean install` build and test completes
- [X] You changed or added to the documentation

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
@bmarwell Can you sign the eclipse CLA? https://accounts.eclipse.org/user/95367/eca/3.1.0

**Comment by bmarwell** [comment]
I tried, but I got my account blocked and need to wait a few days for the next password reset.
But as this is not really code, do you think the CLA is needed?

**Comment by karianna** [comment]
> I tried, but I got my account blocked and need to wait a few days for the next password reset.
> But as this is not really code, do you think the CLA is needed?

I'd have to check with EF CLA on that - chances are your Password reset will arrive first :-)

**Comment by bmarwell** [comment]
Probably not. I cannot enter my password, because the account is blocked. But I cannot use the password reset function either, because the system thinks I haven't reacted to the previous mail. Now I'm stuck.

**Comment by bmarwell** [comment]
@karianna ok had to change my eclipse email address to my a.o one (used that one for commits). Now it did work.

**Pull request merged**
